char = None
line_now = 2
height = 3
width = 30
border = list(width * "#")
line_with_spacecar = list("#"+">00>"+(width - 6 )*" " + "#")
empty_line = list("#" + (width -2)* " " + "#")
i_for_meteorit  = 0
hp = 2
spaces_level  = 7
